// <auto-generated />
using System;
using EstoqueComBD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EstoqueComBD.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220406131805_Todas_Entidades")]
    partial class Todas_Entidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("EstoqueComBD.Model.Entidade.Cliente", b =>
                {
                    b.Property<int>("id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.HasKey("id_cliente");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("EstoqueComBD.Model.Entidade.Entrada", b =>
                {
                    b.Property<int>("id_entrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("data_entrada")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_produto")
                        .HasColumnType("int");

                    b.Property<int>("qtde_entrada")
                        .HasColumnType("int");

                    b.Property<decimal>("valor_entrada")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_entrada");

                    b.ToTable("entrada");
                });

            modelBuilder.Entity("EstoqueComBD.Model.Entidade.Item", b =>
                {
                    b.Property<int>("id_item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("id_produto")
                        .HasColumnType("int");

                    b.Property<int>("id_venda")
                        .HasColumnType("int");

                    b.Property<int>("qtde")
                        .HasColumnType("int");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_item");

                    b.ToTable("item");
                });

            modelBuilder.Entity("EstoqueComBD.Model.Entidade.Produto", b =>
                {
                    b.Property<int>("id_produto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("estoque")
                        .HasColumnType("int");

                    b.Property<decimal>("preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("produto")
                        .HasColumnType("longtext");

                    b.HasKey("id_produto");

                    b.ToTable("produto");
                });

            modelBuilder.Entity("EstoqueComBD.Model.Entidade.Saida", b =>
                {
                    b.Property<int>("id_saida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("data_saida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_produto")
                        .HasColumnType("int");

                    b.Property<int>("qtde_saida")
                        .HasColumnType("int");

                    b.Property<decimal>("valor_saida")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_saida");

                    b.ToTable("saida");
                });

            modelBuilder.Entity("EstoqueComBD.Model.Entidade.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.Property<string>("senha")
                        .HasColumnType("longtext");

                    b.Property<string>("usuario")
                        .HasColumnType("longtext");

                    b.HasKey("id_usuario");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("EstoqueComBD.Model.Entidade.Venda", b =>
                {
                    b.Property<int>("id_venda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("data_venda")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_cliente")
                        .HasColumnType("int");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_venda");

                    b.ToTable("venda");
                });
#pragma warning restore 612, 618
        }
    }
}
