// <auto-generated />
using EstoqueComBD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EstoqueComBD.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220406123030_versao04")]
    partial class versao04
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("EstoqueComBD.Model.Entidade.Produto", b =>
                {
                    b.Property<int>("id_produto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("estoque")
                        .HasColumnType("int");

                    b.Property<decimal>("preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("produto")
                        .HasColumnType("longtext");

                    b.HasKey("id_produto");

                    b.ToTable("produto");
                });
#pragma warning restore 612, 618
        }
    }
}
